/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.20
 * Generated at: 2015-03-23 19:43:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.backend;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/I:/MyWorkspace/DigitalHum/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/digital/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1425845141671L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("@font-face {\r\n");
      out.write("  font-family: 'Lato';\r\n");
      out.write("  font-style: normal;\r\n");
      out.write("  font-weight: 400;\r\n");
      out.write("  src: local('Lato Regular'), local('Lato-Regular'), url(http://themes.googleusercontent.com/static/fonts/lato/v7/qIIYRU-oROkIk8vfvxw6QvesZW2xOQ-xsNqO47m55DA.woff) format('woff');\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("\tbackground: #cbe4fc ;\r\n");
      out.write("\tfont-family: \"Lato\" ;\r\n");
      out.write("}\r\n");
      out.write(".wrap {\r\n");
      out.write("\twidth:250px;\r\n");
      out.write("\theight: auto;\r\n");
      out.write("\tmargin: auto;\r\n");
      out.write("\tmargin-top: 10%;\r\n");
      out.write("}\r\n");
      out.write(".avatar {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tmargin: auto;\r\n");
      out.write("\twidth: 65px;\r\n");
      out.write("\tborder-radius: 100px;\r\n");
      out.write("\theight: 65px;\r\n");
      out.write("\tbackground: #cbe4fc ;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\tbottom: -15px;\r\n");
      out.write("}\r\n");
      out.write(".avatar img {\r\n");
      out.write("\twidth: 55px;\r\n");
      out.write("\theight: 55px;\r\n");
      out.write("\tborder-radius: 100px;\r\n");
      out.write("\tmargin: auto;\r\n");
      out.write("\tborder:3px solid #fff;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("}\r\n");
      out.write(".wrap input {\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\tbackground: #fff;\r\n");
      out.write("  font-family:Lato ;\r\n");
      out.write("  font-weight:700 ;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\theight: 40px;\r\n");
      out.write("\toutline: none;\r\n");
      out.write("\twidth: calc(100% - 24px) ;\r\n");
      out.write("\tmargin: auto;\r\n");
      out.write("\tpadding: 6px 12px 6px 12px;\r\n");
      out.write("}\r\n");
      out.write(".bar {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 1px;\r\n");
      out.write("\tbackground: #fff ;\r\n");
      out.write("}\r\n");
      out.write(".bar i {\r\n");
      out.write("\twidth: 95%;\r\n");
      out.write("\tmargin: auto;\r\n");
      out.write("\theight: 1px ;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tbackground: #d1d1d1;\r\n");
      out.write("}\r\n");
      out.write(".wrap input[type=\"text\"] {\r\n");
      out.write("\tborder-radius: 7px 7px 0px 0px ;\r\n");
      out.write("}\r\n");
      out.write(".wrap input[type=\"password\"] {\r\n");
      out.write("\tborder-radius: 0px 0px 7px 7px ;\r\n");
      out.write("}\r\n");
      out.write(".forgot_link {\r\n");
      out.write("\tcolor: #83afdf ;\r\n");
      out.write("\tcolor: #83afdf;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tfont-size: 11px;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\tleft: 193px;\r\n");
      out.write("\ttop: -36px;\r\n");
      out.write("}\r\n");
      out.write(".wrap input[type=\"submit\"] {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tborder-radius: 7px;\r\n");
      out.write("\tbackground: #b6ee65;\r\n");
      out.write("\ttext-decoration: center;\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\tcolor: #51771a;\r\n");
      out.write("  margin-top:-5px;\r\n");
      out.write("\tpadding-top: 14px;\r\n");
      out.write("\tpadding-bottom: 14px;\r\n");
      out.write("\toutline: none;\r\n");
      out.write("\tfont-size: 13px;\t\r\n");
      out.write("\tborder-bottom: 3px solid #307d63;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\tmargin-top: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".message {\r\n");
      out.write("\twidth:250px;\r\n");
      out.write("\theight: auto;\r\n");
      out.write("\tmargin: auto;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"wrap\">\r\n");
      out.write("\t\t<div class=\"avatar\">\r\n");
      out.write("\t\t\t<img src=\"/backend/images/login/avatar.png\" alt=\"\"/>\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<form method=\"post\" action=\"/backend/j_spring_security_check\">\r\n");
      out.write("\t\t\t<input name=\"j_username\" type=\"text\" placeholder=\"username\" required/>\r\n");
      out.write("\t\t\t<div class=\"bar\">\r\n");
      out.write("\t\t\t\t<i></i>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<input name=\"j_password\" type=\"password\" placeholder=\"password\" required/>\r\n");
      out.write("\t\t\t<input value=\"Login\" type=\"submit\" />\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<br />\r\n");
      out.write("\t<div class=\"message\">\r\n");
      out.write("\t\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /backend/login.jsp(123,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.status=='error'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t<label style=\"color:red\">Invalid username or password!!</label>\r\n");
        out.write("\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent(null);
    // /backend/login.jsp(126,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.status=='logout'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t<label style=\"color:green\">Logged out successfully!</label>\r\n");
        out.write("\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }
}
